sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  global:
      - SYMFONY="~2.6"
install:
  - composer require --no-update symfony/symfony:${SYMFONY}
before_script:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install --no-interaction --prefer-dist
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
